- .github/workflows/django.yml
- config.py
- database/docker-compose-gh.yml
- mongo_models.py
- requirements.txt
- softDsim/settings.py
- tests/test_util/test_config.py
Created a central class that is used for the database configuration management. It automatically read the env vars. Any module and script that required env vars should from now on use a ```Configuration``` class object to do that.
> Feature: #44 central configuration management

- config.py
- mongo_models.py
- tests/test_util/test_config.py
It is now possible to connect from a cloud DB (eg mongo atlas)
> task: #50 enable cloud database in config

- frontend/package-lock.json
- frontend/src/App.jsx
- frontend/src/pages/Simulation.jsx
Created the basic layout of the simulation page
> feature: #106 simulation page initial structure

- app/api_endpoints.py
> refactor: #140 changed template-scenario endpoint to /template-scenario

- frontend/src/components/Navbar.jsx
- frontend/src/pages/Help.jsx
also changed help headlines from german to english
> #155  change simulation studio to scenario studio

- frontend/src/pages/Imprint.jsx
- frontend/src/theme.js
Added Dummy-Content to the imprint and created a basic structure
> task: #164 Write Content for Imprint

- app/api/endpoints.py
- app/api/simulation.py
- app/models/user_scenario.py
- softDsim/urls.py
Mit dem Endpoint startet man ein neues Scenario.
Heißt der User klickt in der Übersicht aller template scenarios auf eines dieser scenarios. Dann wird eine Request an den neuen Endpunkt gesendet:
```
http://127.0.0.1:8000/api/sim/start
```
Im body sind id des template-scenario und id der config:
```json
{
"template-id": 1,
"config-id": 1
}
```
(Die ids müssen natürlich existieren)
Dann bekommtn man als antwort ein UserScenario das frisch in der datenbank erstellt wurde:
```json
{
"status": "success",
"data": {
"id": 6,
"user": {
"id": 11,
"username": "deamon",
"student": true,
"creator": true,
"staff": true,
"admin": true
},
"config": {
"id": 1,
"name": "Some Scenario",
"stress_error_optimum": 0.2,
"stress_weekend_reduction": -0.15,
"stress_overtime_increase": 0.05, …
```
> feature: 186 added endpoint to start user scenario

- frontend/src/pages/Simulation.jsx
Created basic input elements on the simulation dashboard. They don't call any functions yet.
> task: 171 Create Input Elements for Dashboard

- frontend/src/pages/Landing.jsx
setup of an initial landing page
next steps: refine landing page
> task: #112 create landing page

- frontend/src/pages/GDPR.jsx
Setup initial GDPR content. Still needs a better layout and needs to be reworked with GDPR-Group.
> task: #163 setup gdpr content

- frontend/src/Routing.jsx
- frontend/src/components/Navbar.jsx
- frontend/src/pages/Login.jsx
- frontend/src/pages/UserOverview.jsx
every User needs a ".env" file for the substitution while the build process
e.g.: REACT_APP_DJANGO_HOST=http://localhost:8000
> variabel Host & fix substitution

- backend/app/models/team.py
`xp` is a value that can can grow without a max a 1.0
> fix: #135 remove validator from member model

- frontend/src/components/ActionSlider.jsx
- frontend/src/components/ActionSwitch.jsx
- frontend/src/components/ActionToggle.jsx
- frontend/src/components/RadioButton.jsx
- frontend/src/pages/Simulation.jsx
basic setup of components:
- RadioButton
- ActionSlider
- ActionToggle
- ActionSwitch
> task: #218 create basic action components

- frontend/src/pages/Simulation.jsx
> fixed simulation container

- backend/app/models/team.py
- backend/app/src/simulation.py
Ich packe das einfach mal in develop, da wir von dort dann die Feature Branches abzweigen. Tut ja net weh die comments drin zu haben.
> Add Notes for how the simulation logic will run

- backend/app/models/team.py
you can no do
```python
m = Member(...)
hours  = 5
n = m.n_tasks(hours)
```
And *n* will be an integer that is the number of tasks the member can do (solve, fix, test)
> Feature: #318 Added Method to get num Tasks

- backend/app/models/team.py
- backend/app/src/simulation.py
- backend/app/src/util/score_util.py
- backend/history/util/result.py
This build on top of a feature implemented in #359, so we have to merge #359 before we merge this.
> Feature: 277 Scoring Logic

- backend/app/api/views/template_scenario.py
- backend/app/models/simulation_fragment.py
- backend/app/src/util/simulation_util.py
No yet ready to merge because I will implement the use of CachedTasks in here as soon as #359 is merged
> feature: #366 Special Check for Last SimulationFragment

- frontend/src/pages/ScenarioOverview.jsx
scenario.is added to overview list
> added scenario.id to overview list

- frontend/src/pages/GDPR.jsx
- frontend/src/pages/Imprint.jsx
Reworked content and styling for the gdpr page & imprint.
> task: #202 improve gdpr page layout

- backend/app/models/team.py
> task: #321 Create method for action integration_test

- frontend/src/pages/Simulation.jsx
Changed the name of the button to "Deliver Project"
> task: #460 change name of finish early button

- backend/app/api/views/scenario_config.py
- backend/app/dto/response.py
- backend/app/models/scenario.py
- backend/app/models/team.py
- backend/history/models/result.py
- backend/history/util/result.py
-just full randomness or no randomness
-is there another point in the simulation where randomness is used?
> feature: #412 randomness settings for n_tasks

- frontend/src/components/Footer.jsx
- frontend/src/pages/GDPR.jsx
- frontend/src/pages/Imprint.jsx
> task: #513 Final Changes to Legal Pages
